In [18]:
#find local directory
getwd()

#set working directory
setwd("/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis")
getwd()

#set main file path
file_path <- '/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis'
file_path

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis"

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis"

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis"

In [19]:
#load in packages
library(tidyverse)

#load in raw data
political_party <- read.csv(file.path(file_path, "cleaned_datasets/State_Political_Party.csv"))
energy_consumption <- read.csv(file.path(file_path, "cleaned_datasets/State_Energy_Consumptions.csv"))
yearly_policies <- read.csv(file.path(file_path, "cleaned_datasets/State_Yearly_Policies.csv"))

political_party
#head(energy_consumption)
#head(yearly_policies)

     X    State Year Political_Party
1     1   AK    1994 Democrat
2     2   AK    1995 Democrat
3     3   AK    1996 Democrat
4     4   AK    1997 Democrat
5     5   AK    1998 Democrat
6     6   AK    1999 Democrat
7     7   AK    2000 Democrat
8     8   AK    2001 Democrat
9     9   AK    2002 Republican (2nd Gov. mid-year)
10   10   AK    2003 Republican
11   11   AK    2004 Republican
12   12   AK    2005 Republican
13   13   AK    2006 Republican
14   14   AK    2007 Republican
15   15   AK    2008 Republican
16   16   AK    2009 Republican
17   17   AK    2010 Republican
18   18   AK    2011 Republican
19   19   AK    2012 Republican
20   20   AK    2013 Republican
21   21   AK    2014 Independent (2nd Gov. mid-year)
22   22   AK    2015 Independent
23   23   AK    2016 Independent
24   24   AK    2017 Independent
25   25   AK    2018 Independent
26   26   AL    1999 Democrat
27   27   AL    2000 Democrat
28   28   AL    2001 Democrat
29   29   AL    2002 Democrat
30   30   AL    2003 Republican (2nd Gov. mid-year)
⋮    ⋮    ⋮     ⋮    ⋮
1316 1316 WV    2021 Republican
1317 1317 WV    2022 Republican
1318 1318 WV    2023 Republican
1319 1319 WV    2024 Republican
1320 1320 WV    2025 Republican
1321 1321 WY    1995 Republican
1322 1322 WY    1996 Republican
1323 1323 WY    1997 Republican
1324 1324 WY    1998 Republican
1325 1325 WY    1999 Republican
1326 1326 WY    2000 Republican
1327 1327 WY    2001 Republican
1328 1328 WY    2002 Republican
1329 1329 WY    2003 Democrat (2nd Gov. mid-year)
1330 1330 WY    2004 Democrat
1331 1331 WY    2005 Democrat
1332 1332 WY    2006 Democrat
1333 1333 WY    2007 Democrat
1334 1334 WY    2008 Democrat
1335 1335 WY    2009 Democrat
1336 1336 WY    2010 Democrat
1337 1337 WY    2011 Republican (2nd Gov. mid-year)
1338 1338 WY    2012 Republican
1339 1339 WY    2013 Republican
1340 1340 WY    2014 Republican
1341 1341 WY    2015 Republican
1342 1342 WY    2016 Republican
1343 1343 WY    2017 Republican
1344 1344 WY    2018 Republican
1345 1345 WY    2019 Republican

In [20]:
#look at data
#head(political_party)
political_party_NAs <- political_party[!complete.cases(political_party), ]
#political_party_NAs

#head(energy_consumption) 
energy_consumption_NAs <- energy_consumption[!complete.cases(energy_consumption), ]
#energy_consumption_NAs 

#head(yearly_policies) #missing years
yearly_policies_NAs <- energy_consumption[!complete.cases(energy_consumption), ]
#yearly_policies_NAs

In [21]:
#merge political part dataset with energy dataset
all_energy <- political_party %>%
    full_join(energy_consumption, by = c("State", "Year")) %>%
    select(State, Year, Political_Party, Total_Energy, NonRenewable_Energy, NonRenewable_Percent, Renewable_Energy, Renewable_Percent) %>%
    distinct() %>%
   drop_na()
    #filter(Year >= 2000 & Year <= 2023)

all_energy

     State Year Political_Party                 Total_Energy
1    AK    1994 Democrat                         613753
2    AK    1995 Democrat                         694594
3    AK    1996 Democrat                         709979
4    AK    1997 Democrat                         701267
5    AK    1998 Democrat                         715652
6    AK    1999 Democrat                         719766
7    AK    2000 Democrat                         735260
8    AK    2001 Democrat                         726418
9    AK    2002 Republican (2nd Gov. mid-year)   723166
10   AK    2003 Republican                       722838
11   AK    2004 Republican                       765107
12   AK    2005 Republican                       788012
13   AK    2006 Republican                       738306
14   AK    2007 Republican                       714615
15   AK    2008 Republican                       642737
16   AK    2009 Republican                       631141
17   AK    2010 Republican                       629323
18   AK    2011 Republican                       631768
19   AK    2012 Republican                       620717
20   AK    2013 Republican                       587689
21   AK    2014 Independent (2nd Gov. mid-year)  585727
22   AK    2015 Independent                      603471
23   AK    2016 Independent                      582349
24   AK    2017 Independent                      590557
25   AK    2018 Independent                      593777
26   AL    1999 Democrat                        2002228
27   AL    2000 Democrat                        2065056
28   AL    2001 Democrat                        1859587
29   AL    2002 Democrat                        1920029
30   AL    2003 Republican (2nd Gov. mid-year)  1897040
⋮    ⋮     ⋮    ⋮                               ⋮
1293 WV    2019 Republican                      817732
1294 WV    2020 Republican                      786352
1295 WV    2021 Republican                      835873
1296 WV    2022 Republican                      829676
1297 WV    2023 Republican                      832806
1298 WY    1995 Republican                      401562
1299 WY    1996 Republican                      412595
1300 WY    1997 Republican                      411936
1301 WY    1998 Republican                      418381
1302 WY    1999 Republican                      422871
1303 WY    2000 Republican                      425392
1304 WY    2001 Republican                      435687
1305 WY    2002 Republican                      436429
1306 WY    2003 Democrat (2nd Gov. mid-year)    459188
1307 WY    2004 Democrat                        448135
1308 WY    2005 Democrat                        453595
1309 WY    2006 Democrat                        474497
1310 WY    2007 Democrat                        520180
1311 WY    2008 Democrat                        533990
1312 WY    2009 Democrat                        516461
1313 WY    2010 Democrat                        530410
1314 WY    2011 Republican (2nd Gov. mid-year)  543253
1315 WY    2012 Republican                      539195
1316 WY    2013 Republican                      529026
1317 WY    2014 Republican                      524393
1318 WY    2015 Republican                      496831
1319 WY    2016 Republican                      492957
1320 WY    2017 Republican                      522657
1321 WY    2018 Republican                      546375
1322 WY    2019 Republican                      534214
     NonRenewable_Energy NonRenewable_Percent Renewable_Energy
1     599452             98                    14301
2     680919             98                    13675
3     696834             98                    13145
4     693158             99                     8109
5     709568             99                     6084
6     714726             99                     5040
7     729686             99                     5574
8     718299             99                     8119
9     714640             99                     8526
10    713864             99                     8974
11    756143             99                     8964
12    781792             99                     6220
13    732976             99                     5330
14    708941             99                     5674
15    637374             99                     5363
16    623903             99                     7238
17    621530             99                     7793
18    624245             99                     7523
19    612763             99                     7954
20    578749             98                     8940
21    574204             98                    11523
22    589945             98                    13526
23    567978             98                    14371
24    577421             98                    13136
25    580083             98                    13694
26   1764870             88                   237358
27   1841249             89                   223807
28   1664579             90                   195008
29   1726083             90                   193946
30   1697326             89                   199714
⋮    ⋮                   ⋮                    ⋮
1293 785833              96                   31899
1294 760343              97                   26009
1295 809446              97                   26427
1296 801285              97                   28391
1297 804436              97                   28370
1298 396098              99                    5464
1299 406212              98                    6383
1300 405046              98                    6890
1301 411770              98                    6611
1302 416763              99                    6108
1303 418914              98                    6478
1304 429641              99                    6046
1305 431121              99                    5308
1306 453995              99                    5193
1307 442086              99                    6049
1308 444357              98                    9238
1309 465361              98                    9136
1310 510838              98                    9342
1311 523107              98                   10883
1312 501706              97                   14755
1313 511560              96                   18850
1314 518268              95                   24985
1315 515898              96                   23297
1316 505778              96                   23248
1317 500617              95                   23776
1318 471856              95                   24975
1319 465828              94                   27129
1320 494953              95                   27704
1321 520240              95                   26135
1322 506558              95                   27656
     Renewable_Percent
1     2
2     2
3     2
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    2
21    2
22    2
23    2
24    2
25    2
26   12
27   11
28   10
29   10
30   11
⋮    ⋮
1293 4
1294 3
1295 3
1296 3
1297 3
1298 1
1299 2
1300 2
1301 2
1302 1
1303 2
1304 1
1305 1
1306 1
1307 1
1308 2
1309 2
1310 2
1311 2
1312 3
1313 4
1314 5
1315 4
1316 4
1317 5
1318 5
1319 6
1320 5
1321 5
1322 5

In [13]:
#checks for NAs
all_energy_NAs <- all_energy[!complete.cases(all_energy), ]
all_energy_NAs #87 NAs

#missing data for political party

#all_energy2 <- all_energy2 %>% 
#    filter(!(State != "US" & is.na(Political_Party))) #deletes all state Political_Party rows = NA unless US

#all_energy2

     State Year Political_Party Total_Energy NonRenewable_Energy
     NonRenewable_Percent Renewable_Energy Renewable_Percent

In [22]:
#merge political party dataset with politcy dataset
yearly_policies <- political_party %>%
full_join(yearly_policies, by = c("State", "Year")) %>%
    select(State, Year, Political_Party, New_Policies) %>%
    filter(Year >= 2000 & Year <= 2023) %>%
    mutate(New_Policies = replace_na(New_Policies, 0)) %>%
    distinct()
   
yearly_policies

#missing Political Party and policies

     State Year Political_Party                 New_Policies
1    AK    2000 Democrat                        2
2    AK    2001 Democrat                        0
3    AK    2002 Republican (2nd Gov. mid-year)  0
4    AK    2003 Republican                      0
5    AK    2004 Republican                      0
6    AK    2005 Republican                      1
7    AK    2006 Republican                      3
8    AK    2007 Republican                      0
9    AK    2008 Republican                      1
10   AK    2009 Republican                      1
11   AK    2010 Republican                      2
12   AK    2011 Republican                      1
13   AK    2012 Republican                      0
14   AK    2013 Republican                      0
15   AK    2014 Independent (2nd Gov. mid-year) 1
16   AK    2015 Independent                     0
17   AK    2016 Independent                     0
18   AK    2017 Independent                     0
19   AK    2018 Independent                     0
20   AL    2000 Democrat                        1
21   AL    2001 Democrat                        0
22   AL    2002 Democrat                        0
23   AL    2003 Republican (2nd Gov. mid-year)  0
24   AL    2004 Republican                      0
25   AL    2005 Republican                      0
26   AL    2006 Republican                      5
27   AL    2007 Republican                      0
28   AL    2008 Republican                      0
29   AL    2009 Republican                      0
30   AL    2010 Republican                      0
⋮    ⋮     ⋮    ⋮                               ⋮
1148 TX    2016 NA                               3
1149 TX    2018 NA                               1
1150 TX    2019 NA                               2
1151 TX    2021 NA                              11
1152 TX    2022 NA                               2
1153 US    2002 NA                               6
1154 US    2003 NA                               3
1155 US    2004 NA                               1
1156 US    2005 NA                               1
1157 US    2006 NA                               5
1158 US    2007 NA                               1
1159 US    2008 NA                               1
1160 US    2010 NA                               1
1161 US    2012 NA                               1
1162 US    2015 NA                               4
1163 US    2021 NA                               1
1164 US    2022 NA                               3
1165 VI    2005 NA                               1
1166 VI    2007 NA                               1
1167 VI    2009 NA                               2
1168 VI    2014 NA                               2
1169 VT    2019 NA                               2
1170 VT    2021 NA                              22
1171 VT    2022 NA                               1
1172 VT    2023 NA                               6
1173 WI    2021 NA                               8
1174 WI    2023 NA                               1
1175 WV    2011 NA                               1
1176 WV    2012 NA                               2
1177 WY    2020 NA                               2

In [25]:
all_combined_data <- yearly_policies %>%
    full_join(all_energy, by = c("State", "Year", "Political_Party")) %>%
    drop_na()

all_combined_data

     State Year Political_Party                 New_Policies Total_Energy
1    AK    2000 Democrat                        2             735260
2    AK    2001 Democrat                        0             726418
3    AK    2002 Republican (2nd Gov. mid-year)  0             723166
4    AK    2003 Republican                      0             722838
5    AK    2004 Republican                      0             765107
6    AK    2005 Republican                      1             788012
7    AK    2006 Republican                      3             738306
8    AK    2007 Republican                      0             714615
9    AK    2008 Republican                      1             642737
10   AK    2009 Republican                      1             631141
11   AK    2010 Republican                      2             629323
12   AK    2011 Republican                      1             631768
13   AK    2012 Republican                      0             620717
14   AK    2013 Republican                      0             587689
15   AK    2014 Independent (2nd Gov. mid-year) 1             585727
16   AK    2015 Independent                     0             603471
17   AK    2016 Independent                     0             582349
18   AK    2017 Independent                     0             590557
19   AK    2018 Independent                     0             593777
20   AL    2000 Democrat                        1            2065056
21   AL    2001 Democrat                        0            1859587
22   AL    2002 Democrat                        0            1920029
23   AL    2003 Republican (2nd Gov. mid-year)  0            1897040
24   AL    2004 Republican                      0            2017765
25   AL    2005 Republican                      0            2018912
26   AL    2006 Republican                      5            2050932
27   AL    2007 Republican                      0            2067485
28   AL    2008 Republican                      0            1976589
29   AL    2009 Republican                      0            1749863
30   AL    2010 Republican                      0            1906324
⋮    ⋮     ⋮    ⋮                               ⋮            ⋮
1039 WV    2010 Democrat                        1            743395
1040 WV    2015 Democrat                        0            758971
1041 WV    2016 Democrat                        0            752461
1042 WV    2017 Republican (2nd Gov. mid-year)  0            742075
1043 WV    2018 Republican                      0            818371
1044 WV    2019 Republican                      0            817732
1045 WV    2020 Republican                      0            786352
1046 WV    2021 Republican                      0            835873
1047 WV    2022 Republican                      0            829676
1048 WV    2023 Republican                      0            832806
1049 WY    2000 Republican                      0            425392
1050 WY    2001 Republican                      0            435687
1051 WY    2002 Republican                      0            436429
1052 WY    2003 Democrat (2nd Gov. mid-year)    2            459188
1053 WY    2004 Democrat                        0            448135
1054 WY    2005 Democrat                        0            453595
1055 WY    2006 Democrat                        1            474497
1056 WY    2007 Democrat                        5            520180
1057 WY    2008 Democrat                        2            533990
1058 WY    2009 Democrat                        1            516461
1059 WY    2010 Democrat                        0            530410
1060 WY    2011 Republican (2nd Gov. mid-year)  2            543253
1061 WY    2012 Republican                      0            539195
1062 WY    2013 Republican                      0            529026
1063 WY    2014 Republican                      0            524393
1064 WY    2015 Republican                      0            496831
1065 WY    2016 Republican                      0            492957
1066 WY    2017 Republican                      0            522657
1067 WY    2018 Republican                      0            546375
1068 WY    2019 Republican                      1            534214
     NonRenewable_Energy NonRenewable_Percent Renewable_Energy
1     729686             99                     5574
2     718299             99                     8119
3     714640             99                     8526
4     713864             99                     8974
5     756143             99                     8964
6     781792             99                     6220
7     732976             99                     5330
8     708941             99                     5674
9     637374             99                     5363
10    623903             99                     7238
11    621530             99                     7793
12    624245             99                     7523
13    612763             99                     7954
14    578749             98                     8940
15    574204             98                    11523
16    589945             98                    13526
17    567978             98                    14371
18    577421             98                    13136
19    580083             98                    13694
20   1841249             89                   223807
21   1664579             90                   195008
22   1726083             90                   193946
23   1697326             89                   199714
24   1794658             89                   223107
25   1805744             89                   213168
26   1831170             89                   219762
27   1864738             90                   202747
28   1778241             90                   198348
29   1555023             89                   194840
30   1695389             89                   210935
⋮    ⋮                   ⋮                    ⋮
1039 705655              95                   37740
1040 730047              96                   28924
1041 721857              96                   30604
1042 711474              96                   30601
1043 784538              96                   33833
1044 785833              96                   31899
1045 760343              97                   26009
1046 809446              97                   26427
1047 801285              97                   28391
1048 804436              97                   28370
1049 418914              98                    6478
1050 429641              99                    6046
1051 431121              99                    5308
1052 453995              99                    5193
1053 442086              99                    6049
1054 444357              98                    9238
1055 465361              98                    9136
1056 510838              98                    9342
1057 523107              98                   10883
1058 501706              97                   14755
1059 511560              96                   18850
1060 518268              95                   24985
1061 515898              96                   23297
1062 505778              96                   23248
1063 500617              95                   23776
1064 471856              95                   24975
1065 465828              94                   27129
1066 494953              95                   27704
1067 520240              95                   26135
1068 506558              95                   27656
     Renewable_Percent
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    2
15    2
16    2
17    2
18    2
19    2
20   11
21   10
22   10
23   11
24   11
25   11
26   11
27   10
28   10
29   11
30   11
⋮    ⋮
1039 5
1040 4
1041 4
1042 4
1043 4
1044 4
1045 3
1046 3
1047 3
1048 3
1049 2
1050 1
1051 1
1052 1
1053 1
1054 2
1055 2
1056 2
1057 2
1058 3
1059 4
1060 5
1061 4
1062 4
1063 5
1064 5
1065 6
1066 5
1067 5
1068 5

In [26]:
write.csv(all_combined_data, file.path(file_path, "/cleaned_datasets/Combined_Data.csv"))