In [3]:
#find local directory
getwd()

#set working directory
setwd("/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis")
getwd()

#set main file path
file_path <- '/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone'
file_path

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis/cleaned_datasets_scripts"

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis"

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone"

In [4]:
#load in packages
library(tidyverse)

#load in raw data
policy_data <- read.csv(file.path(file_path, "raw_data/State_Clean_Energy_Policies.csv"))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [5]:
#look at data
head(policy_data)

#Want State.Terrtory, Policy.Incentive.Type and Created
    #State.Terrtory -> State
    #Policy.Incentive.Type -> Policy_Type
    #Created -> Year (Want year only)

  Name
1 Alaska Solar Easements
2 Power Project Loan Fund
3 Golden Valley Electric Association - Sustainable Natural Alternative Power (SNAP) Program
4 Energy Efficiency Interest Rate Reduction Program
5 Association Loan Program
6 Building Energy Code
  State.Territory Category            Policy.Incentive.Type       Created
1 AK              Regulatory Policy   Solar/Wind Access Policy    01/01/2000
2 AK              Financial Incentive Loan Program                01/01/2000
3 AK              Financial Incentive Performance-Based Incentive 12/13/2005
4 AK              Financial Incentive Loan Program                05/18/2006
5 AK              Financial Incentive Loan Program                05/18/2006
6 AK              Regulatory Policy   Building Energy Code        08/01/2006
  Last.Updated
1 11/05/2023
2 10/09/2024
3 03/21/2025
4 07/30/2025
5 07/30/2025
6 06/18/2023

In [7]:
#change headings to what I want and to match other datasets
policy_data <- policy_data %>%
    mutate(
        State = State.Territory,
        Policy_Type = Policy.Incentive.Type,
        Year = Created
    ) %>%
    
    #want year only
    mutate(Created = as.Date(Created, format = "%m/%d/%Y")) %>%
    mutate(Year = format(Created, "%Y")) %>% #extract year from full date
    select(State, Year, Name)

policy_data #missing years

     State Year
1    AK    2000
2    AK    2000
3    AK    2005
4    AK    2006
5    AK    2006
6    AK    2006
7    AK    2008
8    AK    2009
9    AK    2010
10   AK    2010
11   AK    2011
12   AK    2014
13   AK    2021
14   AK    2021
15   AK    2021
16   AK    2024
17   AL    2000
18   AL    2006
19   AL    2006
20   AL    2006
21   AL    2006
22   AL    2006
23   AL    2015
24   AL    2015
25   AL    2016
26   AL    2016
27   AL    2020
28   AL    2020
29   AL    2021
30   AL    2022
⋮    ⋮     ⋮
2483 WI    2023
2484 WI    2024
2485 WI    2024
2486 WI    2024
2487 WV    2001
2488 WV    2001
2489 WV    2006
2490 WV    2007
2491 WV    2010
2492 WV    2011
2493 WV    2012
2494 WV    2012
2495 WY    2003
2496 WY    2008
2497 WY    2007
2498 WY    2007
2499 WY    2020
2500 WY    2024
2501 WY    2003
2502 WY    2006
2503 WY    2008
2504 WY    2009
2505 WY    2011
2506 WY    2007
2507 WY    2007
2508 WY    2007
2509 WY    2011
2510 WY    2019
2511 WY    2020
2512 WY    2024
     Name
1    Alaska Solar Easements
2    Power Project Loan Fund
3    Golden Valley Electric Association - Sustainable Natural Alternative Power (SNAP) Program
4    Energy Efficiency Interest Rate Reduction Program
5    Association Loan Program
6    Building Energy Code
7    Renewable Energy Grant Program
8    Net Metering
9    Energy Efficiency Revolving Loan Fund Program
10   Local Option - Property Tax Exemption for Renewable Energy Systems
11   Interconnection Guidelines
12   Weatherization Program
13   Alaska Power and Telephone - AMP-UP Program
14   Chugach Electric - Residential EV Charging Program
15   Chugach Electric - Commercial EV Charging Program
16   Alaska - National Electric Vehicle Infrastructure (NEVI) Formula Grant Program
17   Wood-Burning Heating System Deduction
18   Building Energy Code
19   Central Alabama Electric Cooperative - Residential Energy Efficiency Rebate Program
20   Dixie Electric Cooperative - Residential Energy Efficiency Loan Program
21   Dixie Electric Cooperative - Residential Energy Efficiency Rebate Program
22   South Alabama Electric Cooperative - Residential Energy Efficiency Loan Program
23   TVA - Residential Energy Efficiency Rebate Program
24   Alabama Commercial PACE financing program
25   Voluntary Green Building Standards for Public Buildings
26   Local Option - Property Tax Exemption for Renewable Energy Facilities
27   TVA - Commercial Energy Efficiency Rebate Program
28   Central Alabama Electric Cooperative - Residential Energy Efficiency Loan Program
29   Electric Vehicle Charging Infrastructure Program
30   Alabama Power - Smart Thermostat Reimbursement
⋮    ⋮
2483 Madison Gas & Electric - Charge Ahead Program
2484 Wisconsin - National Electric Vehicle Infrastructure (NEVI) Formula Grant Program
2485 Wisconsin - Home Efficiency Rebate (HER) Program
2486 Wisconsin - Home Electrification and Appliance Rebate (HEAR) Program
2487 Tax Exemption for Renewable Energy Generation
2488 Special Assessment for Wind Energy Systems
2489 Building Energy Code
2490 Net Metering
2491 Interconnection Standards
2492 AEP Appalachian Power - Residential Energy Efficiency Rebate Program
2493 Green Building Standards for Public Buildings
2494 West Virginia Solar Rights
2495 Interconnection Guidelines
2496 Black Hills Energy - Residential Energy Efficiency Rebate Program
2497 Questar Gas - Commercial Energy Efficiency Rebate Program
2498 Questar Gas - Home Builder Gas Appliance Rebate Program
2499 Wyoming Solar Rights
2500 Wyoming - National Electric Vehicle Infrastructure (NEVI) Formula Grant Program
2501 Interconnection Guidelines
2502 Building Energy Code
2503 Black Hills Energy - Residential Energy Efficiency Rebate Program
2504 Rocky Mountain Power - wattsmart Business Program
2505 Lower Valley Energy - Residential Energy Efficiency Rebate Program
2506 Questar Gas - Residential Energy Efficiency Rebate Programs
2507 Questar Gas - Commercial Energy Efficiency Rebate Program
2508 Questar Gas - Home Builder Gas Appliance Rebate Program
2509 Wyoming PACE Financing Program
2510 Black Hills Energy (Electric) - Commercial Energy Efficiency Programs
2511 Wyoming Solar Rights
2512 Wyoming - National Electric Vehicle Infrastructure (NEVI) Formula Grant Program

In [8]:
#create New_Policies, Cumulative_Policies and Past_Policies variables
yearly_policy_data <- policy_data %>%
    select(State, Year) %>%
    group_by(State, Year) %>% #counts number of policy rows by group_by
        mutate(New_Policies = n()) %>%
        distinct()

yearly_policy_data
#do not make cumulative yearly column - have to redo in combined state dataset anyways

    State Year New_Policies
1   AK    2000 2
2   AK    2005 1
3   AK    2006 3
4   AK    2008 1
5   AK    2009 1
6   AK    2010 2
7   AK    2011 1
8   AK    2014 1
9   AK    2021 3
10  AK    2024 1
11  AL    2000 1
12  AL    2006 5
13  AL    2015 2
14  AL    2016 2
15  AL    2020 2
16  AL    2021 1
17  AL    2022 1
18  AL    2023 2
19  AL    2024 2
20  AL    2025 2
21  AR    2006 3
22  AR    2009 7
23  AR    2010 3
24  AR    2014 2
25  AR    2015 2
26  AR    2021 1
27  AR    2023 2
28  AR    2001 1
29  AR    2002 1
30  AR    2011 1
⋮   ⋮     ⋮    ⋮
737 WA    2024  2
738 WI    2000  8
739 WI    2002  1
740 WI    2003  1
741 WI    2006 11
742 WI    2007  2
743 WI    2009  6
744 WI    2010  2
745 WI    2011  3
746 WI    2012  2
747 WI    2015  1
748 WI    2019  1
749 WI    2021  8
750 WI    2023  1
751 WI    2024  3
752 WV    2001  2
753 WV    2006  1
754 WV    2007  1
755 WV    2010  1
756 WV    2011  1
757 WV    2012  2
758 WY    2003  2
759 WY    2008  2
760 WY    2007  5
761 WY    2020  2
762 WY    2024  2
763 WY    2006  1
764 WY    2009  1
765 WY    2011  2
766 WY    2019  1

In [9]:
#checks for NAs
yearly_policy_data_NAs <- yearly_policy_data[!complete.cases(yearly_policy_data), ]
yearly_policy_data_NAs

     State Year New_Policies

In [11]:
write.csv(yearly_policy_data, file.path(file_path, "Lesson_1:Cleaning_Data_for_Analysis/cleaned_datasets/State_Yearly_Policies.csv"))